services:
  wireguard-client:
    image: ghcr.io/vicchi/wireguard-client:${WGCLIENT_VERSION:-latest}
    privileged: true
    restart: unless-stopped
    ports:
      - 9696:9696
    environment:
      - VPN_IP=${VPN_IP}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ./wgnet0.conf:/etc/wireguard/wgnet0.conf
